### PR TITLE
Collection of various changes

### PR DESCRIPTION
**Pull request by Riffecx**

### CODE REVIEW

**Comment by Fennvel** [comment]
The real problem is that by changing the name I had to re-upload the package. This gave it a different signature and it can no longer be updated. This is of course not useful in any way. Hence the whole problem. I apologize for everything.

**Comment by Fennvel** [comment]
Hi @jplight,
Can you please reinstall the package lichesspy on the server. That would be quite important. This is because I have redone the account on PyPi. I apologize for this incident. It will only occur again in a very small number of cases.

**Comment by Riffecx** [comment]
Fix Names @Riffecx

**Review by Riffecx — COMMENTED** [review]
This makes the bot syntax equal to other large bots.

**Comment by Riffecx** [comment]
The manual now also has the correct bot syntax. Before there was still the old one in there.

**Review by Riffecx — COMMENTED** [review]
Change the bot prefix to match the syntax of other bots.

**Comment by Riffecx** [comment]
image
Now let's start with the YouTube patch. 
So, ... YouTube uses 11 random alphanumeric characters to give its videos a unique identifier. We want to adopt that as well.

**Comment by Riffecx** [comment]
Thank you

**Pull request merged**
